apiVersion: apps/v1
kind: Deployment
metadata:
  name: bamboo-agent
  labels:
    app: bamboo-agent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bamboo-agent
  template:
    metadata:
      labels:
        app: bamboo-agent
    spec:
      hostname: bamboo-agent
      initContainers:
      - name: change-home-ownership
        image: busybox
        command: ["/bin/sh","-c","chown -R 1000:1000 /home/bamboo/bamboo-agent-home"]
        volumeMounts:
        - name: bamboo-agent-pv
          mountPath: "/home/bamboo/bamboo-agent-home"
      containers:
      - name: bamboo-agent
        image: alonsomiguel/arm64v8-bamboo-server-agent:7.0.4
        imagePullPolicy: "Always"
        ports:
        volumeMounts:
        - name: bamboo-agent-pv
          mountPath: "/home/bamboo/bamboo-agent-home"
        args: ["https://malonso.me/bamboo"]
        env:
        - name: DOCKER_HOST
          value: tcp://127.0.0.1:2375
      - name: dind
        image: docker:18-dind
        args:
        - "--mtu=1376"
        securityContext:
          privileged: true
        volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker
      nodeSelector:
        k3s.io/hostname: "node03"
      volumes:
      - name: bamboo-agent-pv
        persistentVolumeClaim:
          claimName: bamboo-agent-pvc
      - name: dind-storage
        emptyDir: {}
