apiVersion: v1
kind: PersistentVolume
metadata:
  name: bamboo-agent-pv
  labels:
    app: bamboo-agent
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - lookupcache=pos
    - noatime
  nfs:
    path: /export/ssd/bamboo-agent
    server: node06
