apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bamboo-agent-pvc
  labels:
    app: bamboo-agent
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
